#!/bin/bash

# we'd normally do any dependency stuff here

set -e

. ../venv/bin/activate
pip freeze | grep pytest || pip install pytest

set -x
py.test -o "python_files=test_${PY_VERSION}_*.py test_BOTH_*.py" -s
